apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: jdbc-asterisk-source
  labels:
    strimzi.io/cluster: connect-cluster
spec:
  class: io.confluent.connect.jdbc.JdbcSourceConnector
  tasksMax: 1
  config:
    connection.url: jdbc:mysql://asterisk-db.example.com:3306/asterisk
    connection.user: ${secrets:kafka-connect/jdbc-asterisk-source:username}
    connection.password: ${secrets:kafka-connect/jdbc-asterisk-source:password}
    mode: incrementing
    incrementing.column.name: id
    topic.prefix: asterisk-
    table.whitelist: cdr
    poll.interval.ms: "10000"
