apiVersion: kafka.strimzi.io/v1
kind: KafkaConnect
metadata:
  name: connect-cluster
  annotations:
    strimzi.io/use-connector-resources: "true"
spec:
  version: 4.1.0
  replicas: 1
  image: docker.io/oesolovev/kafka-connect:1.0.0

  bootstrapServers: 10.0.2.9:9092
  groupId: connect-cluster
  offsetStorageTopic: connect-offsets
  configStorageTopic: connect-configs
  statusStorageTopic: connect-status

  config:
    offset.storage.replication.factor: 1
    config.storage.replication.factor: 1
    status.storage.replication.factor: 1
    key.converter: org.apache.kafka.connect.json.JsonConverter
    value.converter: org.apache.kafka.connect.json.JsonConverter
    key.converter.schemas.enable: "false"
    value.converter.schemas.enable: "false"

  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: "1"
      memory: 1Gi

  metricsConfig:
    type: jmxPrometheusExporter
    valueFrom:
      configMapKeyRef:
        name: connect-cluster-metrics
        key: metrics-config.yml

  readinessProbe:
    initialDelaySeconds: 30
    timeoutSeconds: 5
  livenessProbe:
    initialDelaySeconds: 60
    timeoutSeconds: 5

  template:
    pod:
      imagePullSecrets:
        - name: dockerhub-credentials
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9404"
          prometheus.io/path: "/metrics"
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    strimzi.io/cluster: connect-cluster
                    strimzi.io/kind: KafkaConnect
                topologyKey: kubernetes.io/hostname
