apiVersion: v1
kind: ConfigMap
metadata:
  name: connect-cluster-metrics
  labels:
    app: kafka-connect
data:
  metrics-config.yml: |
    lowercaseOutputName: true
    rules:
      - pattern: kafka.connect<type=connect-worker-metrics>([^:]+):
          name: kafka_connect_worker_$1
          type: GAUGE
