apiVersion: kafka.strimzi.io/v1
kind: KafkaConnector
metadata:
  name: test-topic-copy
  labels:
    strimzi.io/cluster: kafka-connect
spec:
  class: org.apache.kafka.connect.mirror.MirrorSourceConnector
  tasksMax: 1
  config:
    source.cluster.alias: source
    target.cluster.alias: target

    source.cluster.bootstrap.servers: 10.0.2.9:9092
    target.cluster.bootstrap.servers: 10.0.2.9:9092

    topics: test-topic

    transforms: rename
    transforms.rename.type: org.apache.kafka.connect.transforms.RegexRouter
    transforms.rename.regex: test-topic
    transforms.rename.replacement: test-topic-copy

    key.converter: org.apache.kafka.connect.storage.StringConverter
    value.converter: org.apache.kafka.connect.storage.StringConverter