name: connect

replicas: 1

bootstrapServers: "10.10.10.1:9092,10.10.10.2:9092,10.10.10.3:9092"

image: "my-registry/kafka-connect:3.8.0"

groupId: "connect-cluster"

offsetTopic: "connect-offsets"
configTopic: "connect-configs"
statusTopic: "connect-status"

replicationFactor: 3